<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Derivation" Id="{6e2d8cc8-4fb7-48c3-b9f7-a8fc414e772e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Derivator
VAR_INPUT
	ss_UpdateMode: SINT;
	f_Signal: LREAL;
END_VAR
VAR_OUTPUT
	f_DerivatedSignal: LREAL;
END_VAR
VAR
	rtb_TSamp: LREAL;
	UD_DSTATE: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>